packages:
  - shared
  - web
  - worker
  - cli
  - vscode-extension

onlyBuiltDependencies:
  - '@sentry/cli'
  - bufferutil
  - esbuild
  - esbuild-plugin-define
  - esbuild-plugin-environment
  - fsevents
  - node-datachannel
  - sharp
  - unrs-resolver
  - utf-8-validate
  - workerd

publicHoistPattern:
  - next
