[package]
name = "deadrop"
version = "0.3.1"
description = "End-to-end encrypted secret sharing"
authors = ["Nieky Allen <nieky.allen@gmail.com>"]
edition = "2021"
license = "MIT"
homepage = "https://deadrop.io"
repository = "https://github.com/dallen4/deadrop"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "deadrop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = { version = "4.1.5", features = [
    "apple-native-keyring-store",
    "windows-native-keyring-store",
    "zbus-secret-service-keyring-store",
] }
tauri-plugin-http = { version = "2.5.9", features = ["unsafe-headers"] }
libsql = { version = "0.9.30", features = ["remote", "replication"] }
tokio = { version = "1.53.1", features = ["time"] }
tauri-plugin-fs = "2.5.1"
tauri-plugin-dialog = "2"

