// @ts-nocheck
import { build } from 'bun';
import { platform, arch } from 'os';
import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

// Generate bun-inject.ts with static requires for the current platform.
// Bun's bundler needs literal string requires to trace and embed .node files.
const p = platform();
const a = arch();
const sysCode = `${p}-${a}`;

// libsql platform-tagged packages: darwin-{arm64,x64}, linux-{arm64,x64}-gnu, win32-x64-msvc
const libsqlSuffixMap: Record<string, string> = {
  'darwin-arm64': 'darwin-arm64',
  'darwin-x64': 'darwin-x64',
  'linux-x64': 'linux-x64-gnu',
  'linux-arm64': 'linux-arm64-gnu',
  'win32-x64': 'win32-x64-msvc',
};
const libsqlSuffix = libsqlSuffixMap[sysCode];
if (!libsqlSuffix) {
  console.error(`Unsupported platform for libsql: ${sysCode}`);
  process.exit(1);
}

const templatePath = resolve(
  import.meta.dir,
  './bun-inject.template.ts',
);
const injectPath = resolve(import.meta.dir, '../lib/bun-inject.ts');

// Read figlet Standard font at build time to inline in bun-inject.ts
const figletPkgDir = resolve(require.resolve('figlet'), '..', '..');
const figletFontPath = resolve(figletPkgDir, 'fonts', 'Standard.flf');
const figletFontData = readFileSync(figletFontPath, 'utf8');

const tokens: Record<string, string> = {
  __LIBSQL_SUFFIX__: libsqlSuffix,
};

const generatedHeader = `// THIS FILE IS GENERATED by scripts/bun-build.ts from scripts/bun-inject.template.ts.
// Do not edit manually — edits will be overwritten on next compile.
// Target platform: ${sysCode}

`;

const injectContent =
  generatedHeader +
  Object.entries(tokens).reduce(
    (src, [token, value]) => src.split(token).join(value),
    readFileSync(templatePath, 'utf8'),
  );

writeFileSync(injectPath, injectContent);
console.log(`Generated bun-inject.ts for ${sysCode}`);

const env = {
  DEADROP_API_URL: process.env.DEADROP_API_URL!,
  DEADROP_APP_URL: process.env.DEADROP_APP_URL!,
  PEER_SERVER_URL: process.env.PEER_SERVER_URL!,
  CLERK_PUBLISHABLE_KEY: process.env.CLERK_PUBLISHABLE_KEY!,
};

if (!env.DEADROP_API_URL || !env.PEER_SERVER_URL) {
  console.error('Invalid environment configuration');
  process.exit(1);
}

const envVars = Object.fromEntries(
  Object.entries(env).map(([k, v]) => [
    `process.env.${k}`,
    JSON.stringify(v),
  ]),
);

// Inject figlet font data as a build-time constant
envVars['FIGLET_STANDARD_FONT'] = JSON.stringify(figletFontData);

console.log(envVars);

// @ts-expect-error Top-level await is valid in Bun
await build({
  entrypoints: ['./index.ts'],
  compile: {
    target: `bun-${sysCode}`,
    outfile: './dist/deadrop',
  },
  naming: 'deadrop',
  minify: true,
  define: envVars,
});
