# docs: https://developers.cloudflare.com/workers
"$schema" = "./node_modules/wrangler/config-schema.json"
name = "deadrop"
main = "src/index.ts"
compatibility_date = "2023-11-21"

# production environment configurations

[route]
pattern = "deadrop.nieky.dev"
custom_domain = true

# ref: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "DROP_STORE"
id = "0ab3b4313ce542d8af187a5f881dcbb1"
preview_id = "a3d27b9d9c6841a9969cd9e07a73c9ff"

[[durable_objects.bindings]]
name = "PEER_SERVER"
class_name = "PeerServerDO"

[[migrations]]
tag = "v1"  # must be unique for each entry
new_classes = ["PeerServerDO"]

[observability]
enabled = true
logs.enabled = true
logs.invocation_logs = true

# alpha environment configurations

[env.alpha.route]
pattern = "alpha.deadrop.nieky.dev"
custom_domain = true

[[env.alpha.kv_namespaces]]
binding = "DROP_STORE"
id = "a3d27b9d9c6841a9969cd9e07a73c9ff"

[[env.alpha.durable_objects.bindings]]
name = "PEER_SERVER"
class_name = "PeerServerDO"
