name: Release CLI
on:
  push:
    tags:
      - "cli-v*"
jobs:
  cli-package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build CLI
        shell: bash
        env:
          PEER_SERVER_URL: ${{ secrets.PEER_SERVER_URL }}
          TURN_USERNAME: ${{ secrets.TURN_USERNAME }}
          TURN_PWD: ${{ secrets.TURN_PWD }}
          DEADROP_API_URL: ${{ secrets.DEADROP_API_URL }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          cd cli
          yarn install --frozen-lockfile
          echo $DEADROP_API_URL
          echo $PEER_SERVER_URL
          export DEADROP_API_URL=$DEADROP_API_URL
          export PEER_SERVER_URL=$PEER_SERVER_URL
          export TURN_USERNAME=$TURN_USERNAME
          export TURN_PWD=$TURN_PWD
          yarn build
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ./.npmrc
          npm publish
      # - uses: marvinpinto/action-automatic-releases@latest
      #   if: steps.cache-bundle.outputs.cache-hit != 'true'
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     draft: true
      #     prerelease: false
      #     files: cli/dist/deadrop-*
