name: Version Bump
on:
  workflow_dispatch:
    inputs:
      pkg_name:
        type: choice
        description: Package to Release
        options:
        - web
        - cli
        - worker
        - shared
      rel_type:
        type: choice
        description: Type of Release
        options:
        - patch
        - minor
        - major

jobs:
  pkg-version-bump:
    if: github.event.inputs.pkg_name != 'shared'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Version Bump
        run: |
          cd ${{ github.event.inputs.pkg_name }}
          npm version ${{ github.event.inputs.rel_type }} --tag-version-prefix="${{ github.event.inputs.pkg_name }}-v"
  platform-version-bump:
    if: github.event.inputs.pkg_name == 'shared'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Version Bump
        run: |
          cd web
          npm version ${{ github.event.inputs.rel_type }} --tag-version-prefix="web-v"
          echo "bumped web version"

          cd ../cli
          npm version ${{ github.event.inputs.rel_type }} --tag-version-prefix="cli-v"
          echo "bumped cli version"

          cd ../worker
          npm version ${{ github.event.inputs.rel_type }} --tag-version-prefix="worker-v"
          echo "bumped worker version"

          cd ../shared
          npm version ${{ github.event.inputs.rel_type }} --tag-version-prefix="shared-v"
          echo "bumped shared version"

          cd ..
          npm version ${{ github.event.inputs.rel_type }} --tag-version-prefix="v"
          echo "bumped platform version"
          
          git push
          git push origin --tags
