name: Version Bump
on:
  workflow_dispatch:
    inputs:
      pkg_name:
        type: choice
        description: Package to Release
        options: 
        - web
        - cli
        - worker
        - shared
      rel_type:
        type: choice
        description: Type of Release
        options: 
        - patch
        - minor
        - major

jobs:
  pkg-version-bump:
    if: github.event.inputs.pkg_name != 'shared'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Version Bump
        run: |
          yarn config set version-tag-prefix "${{ github.event.inputs.pkg_name }}-v"
          yarn ${{ github.event.inputs.pkg_name }} version --${{ github.event.inputs.rel_type }}
  platform-version-bump:
    if: github.event.inputs.pkg_name == 'shared'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Version Bump
        run: |
          yarn config set version-tag-prefix "web-v"
          yarn web version --${{ github.event.inputs.rel_type }}
          echo "bumped web version"

          yarn config set version-tag-prefix "cli-v"
          yarn cli version --${{ github.event.inputs.rel_type }}
          echo "bumped cli version"

          yarn config set version-tag-prefix "shared-v"
          yarn shared version --${{ github.event.inputs.rel_type }}
          echo "bumped shared version"

          yarn config set version-tag-prefix "v"
          yarn version --${{ github.event.inputs.rel_type }}
          echo "bumped platform version"
