name: Playwright Tests

on:
  deployment_status:

jobs:
  test:
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: yarn web playwright install --with-deps
      - name: Run Playwright Tests
        shell: bash
        env:
          STAGE: ${{ github.ref_name }}
          BASE_URL: ${{ github.event.deployment_status.target_url }}
          DEADROP_API_URL: ${{ secrets.DEADROP_API_URL }}
        run: |
          echo $DEADROP_API_URL
          export DEADROP_API_URL=$DEADROP_API_URL
          echo $TEST_URI
          export TEST_URI=$BASE_URL
          CI=true yarn web playwright test --trace on
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: web/test-results/
          retention-days: 30
