name: Playwright Tests
on:
  push:
    branches: [main, alpha]
jobs:
  test:
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: yarn web playwright install --with-deps
      - name: Run Playwright Tests
        shell: bash
        env:
          STAGE: ${{ github.ref_name }}
        run: |
          if [[ $STAGE == "alpha" ]]; then BASE_URI="https://test.drop.nieky.dev"; else BASE_URI="https://drop.nieky.dev"; fi
          CI=true TEST_URI=$BASE_URI yarn web playwright test --trace on
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: test-results/
          retention-days: 30
